AWSTemplateFormatVersion: 2010-09-09
Description: template for ec2 instance creation

Parameters:
  EnvironmentName: 
   Description: type SDLC env name. eg.dev/prod/qa
   Type: String

Resources: 
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: AWS-KEY-JULY-2022  
      InstanceType: t2.micro
      ImageId: 'ami-026b57f3c383c2eec'
  InstanceSecurityGroup: 
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Join [ "-", [ !Ref EnvironmentName, 'ec2-security-group' ] ]
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 